CREATE DATABASE INVENTARIO;
USE INVENTARIO;

CREATE TABLE PRODUCTOS(
PRO_CODIGO_K VARCHAR(20) NOT NULL,
PRO_DESCRIPCION VARCHAR(120) NOT NULL,
PRO_PRECIO DOUBLE,
PRO_FECHA DATE,
PRIMARY KEY (PRO_CODIGO_K)
);

CREATE TABLE EXISTENCIAS(
PRO_CODIGO_K VARCHAR(20) NOT NULL,
EXI_LOTE VARCHAR(20) NOT NULL,
EXI_CANTIDAD DOUBLE NOT NULL,
PRIMARY KEY (PRO_CODIGO_K, EXI_LOTE),
FOREIGN KEY (PRO_CODIGO_K) REFERENCES PRODUCTOS (PRO_CODIGO_K)
);


CREATE TABLE MOVIMIENTOS(
MOV_CODIGO_K INTEGER NOT NULL,
MOV_MOVIMIENTO VARCHAR(3) DEFAULT 'ENT',
MOV_FECHA DATE,
PRO_CODIGO_K VARCHAR(20),
EXI_LOTE VARCHAR(20),
MOV_COSTO DOUBLE,
MOV_CANTIDAD DOUBLE,
MOV_TOTAL DOUBLE,
PRIMARY KEY (MOV_CODIGO_K,PRO_CODIGO_K,EXI_LOTE),
FOREIGN KEY( PRO_CODIGO_K ) REFERENCES PRODUCTOS ( PRO_CODIGO_K )
);

DELIMITER $$
CREATE OR REPLACE TRIGGER MOVIMIENTO_TRIGGER
BEFORE INSERT ON MOVIMIENTOS
FOR EACH ROW
BEGIN
IF NEW.MOV_MOVIMIENTO = 'ENT' THEN
UPDATE EXISTENCIAS
SET EXI_CANTIDAD = EXI_CANTIDAD + NEW.MOV_CANTIDAD
WHERE PRO_CODIGO_K = NEW.PRO_CODIGO_K AND EXI_LOTE=NEW.EXI_LOTE;

END IF;
IF NEW.MOV_MOVIMIENTO = 'SAL' THEN
UPDATE EXISTENCIAS
SET EXI_CANTIDAD = EXI_CANTIDAD - NEW.MOV_CANTIDAD
WHERE PRO_CODIGO_K = NEW.PRO_CODIGO_K AND EXI_LOTE=NEW.EXI_LOTE;
END IF;
SET NEW.MOV_TOTAL=NEW.MOV_COSTO*NEW.MOV_CANTIDAD;
END
$$
DELIMITER ;

DELIMITER $$
CREATE OR REPLACE TRIGGER MOVTOTAL_TRIGGER
BEFORE INSERT ON MOVIMIENTOS
FOR EACH ROW
BEGIN
SET NEW.MOV_TOTAL=NEW.MOV_COSTO*NEW.MOV_CANTIDAD;
END
$$
DELIMITER ;

CREATE VIEW VISTA_PRODUCTOS_EXISTENCIAS AS
SELECT 
P.PRO_CODIGO_K,
P.PRO_DESCRIPCION,
P.PRO_PRECIO,
P.PRO_FECHA,
E.EXI_LOTE,
E.EXI_CANTIDAD
FROM PRODUCTOS P
INNER JOIN EXISTENCIAS E
ON P.PRO_CODIGO_K = E.PRO_CODIGO_K;
